### ISSUE TITLE
Template parse error for: <a[routerLink]="['/']">Home</a> issue

### ISSUE THREAD

**Issue by jeffschwartz** [angular/vladivostok#66]
Browser exception:

```html
EXCEPTION: Template parse errors:
Unexpected closing tag "a" ("
    <h1>Preamble BDD</h1>
    <ul>
        <li><a[routerLink]="['/']">Home[ERROR ->]</a></li>
        <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]=""): AppComponent@3:39
Unexpected closing tag "a" ("      <li><a[routerLink]="['/']">Home</a></li>
        <li><a[routerLink]="['/changelog']">Changelog[ERROR ->]</a></li>
        <li><a[routerLink]="['/api']">API</a></li>
    </ul>
"): AppComponent@4:53
Unexpected closing tag "a" ("    <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]="['/api']">API[ERROR ->]</a></li>
    </ul>
</nav>
"): AppComponent@5:41
```

My app.routes.ts:
```typescript
import { HomeComponent } from "./home.component";
import { ApiComponent } from "./api.component";
import { ChangeLogComponent } from "./changelog.component";

export const appRoutes = [
    {path: "/", component: HomeComponent },
    {path: "/changelog", component: ChangeLogComponent },
    {path: "/api", component: ApiComponent }
];
```

My main.ts:
```typescript
import { provideRouter } from "@angular/router";
import { bootstrap }    from "@angular/platform-browser-dynamic";
import { Title } from "@angular/platform-browser";
import { AppComponent } from "./app.component";
import { appRoutes } from "./app.routes";

bootstrap(AppComponent, [
    provideRouter(appRoutes),
    Title
]).catch(err => console.error(err));
```

My app.component.html:
```html
<nav>
    <h1>Preamble BDD</h1>
    <ul>
        <li><a[routerLink]="['/']">Home</a></li>
        <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]="['/api']">API</a></li>
    </ul>
</nav>
<router-outlet></router-outlet>
```

My app.component.ts:
```typescript
import {Component} from "@angular/core";

@Component({
    selector: "my-app",
    templateUrl: "app/app.component.html",
    styleUrls: ["app/app.component.css"]
})

export class AppComponent { }
```

**Comment by jeffschwartz** [comment]
Here is the complete console log output:

```
EXCEPTION: Template parse errors:
Unexpected closing tag "a" ("
    <h1>Preamble BDD</h1>
    <ul>
        <li><a[routerLink]="['/']">Home[ERROR ->]</a></li>
        <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]=""): AppComponent@3:39
Unexpected closing tag "a" ("      <li><a[routerLink]="['/']">Home</a></li>
        <li><a[routerLink]="['/changelog']">Changelog[ERROR ->]</a></li>
        <li><a[routerLink]="['/api']">API</a></li>
    </ul>
"): AppComponent@4:53
Unexpected closing tag "a" ("    <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]="['/api']">API[ERROR ->]</a></li>
    </ul>
</nav>
"): AppComponent@5:41
EXCEPTION: Template parse errors:
Unexpected closing tag "a" ("
    <h1>Preamble BDD</h1>
    <ul>
        <li><a[routerLink]="['/']">Home[ERROR ->]</a></li>
        <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]=""): AppComponent@3:39
Unexpected closing tag "a" ("      <li><a[routerLink]="['/']">Home</a></li>
        <li><a[routerLink]="['/changelog']">Changelog[ERROR ->]</a></li>
        <li><a[routerLink]="['/api']">API</a></li>
    </ul>
"): AppComponent@4:53
Unexpected closing tag "a" ("    <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]="['/api']">API[ERROR ->]</a></li>
    </ul>
</nav>
"): AppComponent@5:41
BaseException$1 {message: "Template parse errors:↵Unexpected closing tag "a" …]</a></li>↵    </ul>↵</nav>↵"): AppComponent@5:41", stack: "Error: Template parse errors:↵Unexpected closing t…dules/@angular/core//bundles/core.umd.js:8996:45)"}message: "Template parse errors:↵Unexpected closing tag "a" ("↵    <h1>Preamble BDD</h1>↵    <ul>↵        <li><a[routerLink]="['/']">Home[ERROR ->]</a></li>↵        <li><a[routerLink]="['/changelog']">Changelog</a></li>↵        <li><a[routerLink]=""): AppComponent@3:39↵Unexpected closing tag "a" ("      <li><a[routerLink]="['/']">Home</a></li>↵        <li><a[routerLink]="['/changelog']">Changelog[ERROR ->]</a></li>↵        <li><a[routerLink]="['/api']">API</a></li>↵    </ul>↵"): AppComponent@4:53↵Unexpected closing tag "a" ("    <li><a[routerLink]="['/changelog']">Changelog</a></li>↵        <li><a[routerLink]="['/api']">API[ERROR ->]</a></li>↵    </ul>↵</nav>↵"): AppComponent@5:41"stack: "Error: Template parse errors:↵Unexpected closing tag "a" ("↵    <h1>Preamble BDD</h1>↵    <ul>↵        <li><a[routerLink]="['/']">Home[ERROR ->]</a></li>↵        <li><a[routerLink]="['/changelog']">Changelog</a></li>↵        <li><a[routerLink]=""): AppComponent@3:39↵Unexpected closing tag "a" ("      <li><a[routerLink]="['/']">Home</a></li>↵        <li><a[routerLink]="['/changelog']">Changelog[ERROR ->]</a></li>↵        <li><a[routerLink]="['/api']">API</a></li>↵    </ul>↵"): AppComponent@4:53↵Unexpected closing tag "a" ("    <li><a[routerLink]="['/changelog']">Changelog</a></li>↵        <li><a[routerLink]="['/api']">API[ERROR ->]</a></li>↵    </ul>↵</nav>↵"): AppComponent@5:41↵    at new BaseException$1 (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:955:27)↵    at DirectiveNormalizer.normalizeLoadedTemplate (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:11698:23)↵    at eval (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:11687:69)↵    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:323:29)↵    at Object.onInvoke (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:9005:45)↵    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:322:35)↵    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:216:44)↵    at http://localhost:3000/node_modules/zone.js/dist/zone.js:571:58↵    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:356:38)↵    at Object.onInvokeTask (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:8996:45)"__proto__: Error
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Unexpected closing tag "a" ("
    <h1>Preamble BDD</h1>
    <ul>
        <li><a[routerLink]="['/']">Home[ERROR ->]</a></li>
        <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]=""): AppComponent@3:39
Unexpected closing tag "a" ("      <li><a[routerLink]="['/']">Home</a></li>
        <li><a[routerLink]="['/changelog']">Changelog[ERROR ->]</a></li>
        <li><a[routerLink]="['/api']">API</a></li>
    </ul>
"): AppComponent@4:53
Unexpected closing tag "a" ("    <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]="['/api']">API[ERROR ->]</a></li>
    </ul>
</nav>
"): AppComponent@5:41
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Unexpected closing tag "a" ("
    <h1>Preamble BDD</h1>
    <ul>
        <li><a[routerLink]="['/']">Home[ERROR ->]</a></li>
        <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]=""): AppComponent@3:39
Unexpected closing tag "a" ("      <li><a[routerLink]="['/']">Home</a></li>
        <li><a[routerLink]="['/changelog']">Changelog[ERROR ->]</a></li>
        <li><a[routerLink]="['/api']">API</a></li>
    </ul>
"): AppComponent@4:53
Unexpected closing tag "a" ("    <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]="['/api']">API[ERROR ->]</a></li>
    </ul>
</nav>
"): AppComponent@5:41
STACKTRACE:
Error: Uncaught (in promise): Template parse errors:
Unexpected closing tag "a" ("
    <h1>Preamble BDD</h1>
    <ul>
        <li><a[routerLink]="['/']">Home[ERROR ->]</a></li>
        <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]=""): AppComponent@3:39
Unexpected closing tag "a" ("      <li><a[routerLink]="['/']">Home</a></li>
        <li><a[routerLink]="['/changelog']">Changelog[ERROR ->]</a></li>
        <li><a[routerLink]="['/api']">API</a></li>
    </ul>
"): AppComponent@4:53
Unexpected closing tag "a" ("    <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]="['/api']">API[ERROR ->]</a></li>
    </ul>
</nav>
"): AppComponent@5:41
    at resolvePromise (zone.js:538)
    at zone.js:574
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.onInvokeTask (core.umd.js:8996)
    at ZoneDelegate.invokeTask (zone.js:355)
    at Zone.runTask (zone.js:256)
    at drainMicroTaskQueue (zone.js:474)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:426)
Unhandled Promise rejection: Template parse errors:
Unexpected closing tag "a" ("
    <h1>Preamble BDD</h1>
    <ul>
        <li><a[routerLink]="['/']">Home[ERROR ->]</a></li>
        <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]=""): AppComponent@3:39
Unexpected closing tag "a" ("      <li><a[routerLink]="['/']">Home</a></li>
        <li><a[routerLink]="['/changelog']">Changelog[ERROR ->]</a></li>
        <li><a[routerLink]="['/api']">API</a></li>
    </ul>
"): AppComponent@4:53
Unexpected closing tag "a" ("    <li><a[routerLink]="['/changelog']">Changelog</a></li>
        <li><a[routerLink]="['/api']">API[ERROR ->]</a></li>
    </ul>
</nav>
"): AppComponent@5:41 ; Zone: angular ; Task: Promise.then ; Value: BaseException$1 {message: "Template parse errors:↵Unexpected closing tag "a" …]</a></li>↵    </ul>↵</nav>↵"): AppComponent@5:41", stack: "Error: Template parse errors:↵Unexpected closing t…dules/@angular/core//bundles/core.umd.js:8996:45)"}
Error: Uncaught (in promise): Template parse errors:(…)
```

**Comment by dloukadakis** [comment]
You need a space between tag and attributes.

Example:
`<a[routerLink]` -> `<a [routerLink]`

**Comment by jeffschwartz** [comment]
Thanks @dloukadakis but with

```html
<nav>
    <h1>Preamble BDD</h1>
    <ul>
        <li><a [routerLink]="['/']">Home</a></li>
        <li><a [routerLink]="['/changelog']">Changelog</a></li>
        <li><a [routerLink]="['/api']">API</a></li>
    </ul>
</nav>
<router-outlet></router-outlet>
```
I still get

```
EXCEPTION: Template parse errors:
Can't bind to 'routerLink' since it isn't a known native property ("
    <h1>Preamble BDD</h1>
    <ul>
        <li><a [ERROR ->][routerLink]="['/']">Home</a></li>
        <li><a [routerLink]="['/changelog']">Changelog</a></li>
  "): AppComponent@3:15
Can't bind to 'routerLink' since it isn't a known native property ("
    <ul>
        <li><a [routerLink]="['/']">Home</a></li>
        <li><a [ERROR ->][routerLink]="['/changelog']">Changelog</a></li>
        <li><a [routerLink]="['/api']">API</a></li>
"): AppComponent@4:15
Can't bind to 'routerLink' since it isn't a known native property ("['/']">Home</a></li>
        <li><a [routerLink]="['/changelog']">Changelog</a></li>
        <li><a [ERROR ->][routerLink]="['/api']">API</a></li>
    </ul>
</nav>
"): AppComponent@5:15
```

**Comment by dloukadakis** [comment]
You didn't add ROUTER_DIRECTIVES to your component directives.

**Comment by jeffschwartz** [comment]
@dloukadakis yup, ROUTER_DIRECTIVES was the issue. Thanks. I'll try not to bother you all with stupid stuff :)
